services:
  laravel.test:
    container_name: ${APP_NAME}-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP}
    image: laravel-restful-api/${APP_NAME}
    ports:
      - ${APP_HTTP_PORT:-8000}:8000
    environment:
      WWWUSER: ${WWWUSER}
      LARAVEL_SAIL: 1
    volumes:
      - .:/var/www/html
    networks:
      - "laravel-network"
    healthcheck:
      test: curl --fail -s http://127.0.0.1:80/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - mysql
      - redis
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:8.0
    privileged: false
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - vmysql:/var/lib/mysql
    networks:
      - "laravel-network"
    ports:
      - ${MYSQL_PORT:-3306}:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin
    privileged: false
    security_opt:
      - no-new-privileges:true
    ports:
      - ${FORWARD_PHPMYADMIN_PORT:-8080}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - "laravel-network"
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:alpine
    privileged: false
    security_opt:
      - no-new-privileges:true
    volumes:
      - "vredis:/data"
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    networks:
      - "laravel-network"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 45s
      interval: 10s
      retries: 10
networks:
  laravel-network:
    name: ${APP_NAME}-network
    driver: bridge
volumes:
  vmysql:
    driver: local
  vredis:
    driver: local
